"""Added tff video index

Revision ID: 69802cf26a68
Revises:
Create Date: 2024-05-20 17:56:48.983295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69802cf26a68"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tracking_frame_feature_video_id"), "tracking_frame_feature", ["video_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_frame_feature_video_id"), table_name="tracking_frame_feature")
    # ### end Alembic commands ###
