"""Add TFF index

Revision ID: bc2a126519ab
Revises: 69802cf26a68
Create Date: 2024-05-29 14:22:09.066504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2a126519ab'
down_revision: Union[str, None] = '69802cf26a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tracking_id_frame_nr_feature_type', 'tracking_frame_feature', ['tracking_id', 'frame_nr', 'feature_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracking_id_frame_nr_feature_type', table_name='tracking_frame_feature')
    # ### end Alembic commands ###
